### ISSUE TITLE
Remediate template warnings

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/pictoralist#53]
A result of putting the templates under test in #52 is a few warnings being thrown.  The issues surrounding them don't appear to be breaking.  All appear to be minor changes.

-----
```
test_integration_builtin_templates.r:15: warning: Baked in templates with single time points work with mtx data
Ignoring unknown parameters: fill
```
Likely `fill` passed as an aesthetic or argument to a geom that doesn't use it.

-----
```
test_integration_builtin_templates.r:28: warning: Baked in templates with single time points work with va data
no non-missing arguments to min; returning Inf
```
Possibly NA in a vector passed to `max()`.  Likely `na.rm=T` will solve the issue or reveal an underlying problem.

-----
```
test_integration_builtin_templates.r:28: warning: Baked in templates with single time points work with va data
no non-missing arguments to max; returning -Inf
```
Possibly NA in a vector passed to `max()`.  Likely `na.rm=T` will solve the issue or reveal an underlying problem.

-----
```
test_integration_builtin_templates.r:129: warning: Data provided is used in ComparisonBarGraphVERT
Ignoring unknown parameters: fill
```
Likely `fill` passed as an aesthetic to a geom that doesn't use it.

-----
```
test_integration_builtin_templates.r:243: warning: Data provided is used in baked in ComparisonLineGraph
number of items to replace is not a multiple of replacement length
```
This might be trickier to track down.  There is a data manipulation that is not guaranteed to have a copacetic length.  Maybe an vector assignment to a subset of a dataframe or other vector.

**Comment by b-sheppard** [comment]
- [x] test_integration_builtin_templates.r:15
- [ ] test_integration_builtin_templates.r:28
- [ ] test_integration_builtin_templates.r:28
- [ ] test_integration_builtin_templates.r:129
- [ ] test_integration_builtin_templates.r:243
- [ ] test_produce_plots.R:65

**Comment by b-sheppard** [comment]
For issues 1 and 4, geom_text does not accept the parameter "fill"
